# Utilisez l'image de base avec MkDocs et le thème Material
FROM squidfunk/mkdocs-material

# Installez les dépendances supplémentaires ici, si nécessaire
# RUN pip install --no-cache-dir package_name==version
